version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
       POSTGRES_USER: ashiq
       POSTGRES_PASSWORD: ashiq123
       POSTGRES_DB: shiftsync_db
    networks:
      - mynetwork

  api:
    build: . 
    image: ashiq328/shiftsync:1.0
    ports: 
      - 8081:8081
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
