// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"shiftsync/pkg/api"
	"shiftsync/pkg/api/handler"
	"shiftsync/pkg/usecases"
)

// Injectors from wire.go:

func InitializeAPI() *http.ServerHTTP {
	employeeUseCase := usecases.NewEmployeeUseCase()
	employeeHandler := handler.NewEmployeeHandler(employeeUseCase)
	serverHTTP := http.NewHTTPServer(employeeHandler)
	return serverHTTP
}
