// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"shiftsync/pkg/api"
	"shiftsync/pkg/api/handler"
	"shiftsync/pkg/config"
	"shiftsync/pkg/db"
	"shiftsync/pkg/repository"
	"shiftsync/pkg/usecases"
)

// Injectors from wire.go:

func InitializeAPI(config2 config.Config) *http.ServerHTTP {
	gormDB := db.ConnectToDatbase(config2)
	employeeRepository := repository.NewEmployeeRepository(gormDB)
	employeeUseCase := usecases.NewEmployeeUseCase(employeeRepository)
	employeeHandler := handler.NewEmployeeHandler(employeeUseCase)
	adminRepository := repository.NewAdminRepository(gormDB, employeeRepository)
	adminUseCase := usecases.NewAdminUseCase(adminRepository)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	serverHTTP := http.NewHTTPServer(employeeHandler, adminHandler)
	return serverHTTP
}
