apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiftsync-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiftsync 
  template:
    metadata:
      labels:
        app: shiftsync
    spec:
      containers:
        - name: shiftsync
          image: ashiq328/shiftsync:2.0
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: shiftsync-service
spec:
  selector:
    app: shiftsync
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
 