name: shiftSync

on: 
  push:
    branches: [ testing ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.5

      - name: Install Make
        run: |
          sudo apt update
          sudo apt install -y make

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Connect to EC2 instance
        run: ssh -i ${{ secrets.SSH_KEY }} ubuntu@ec2-34-228-140-218.compute-1.amazonaws.com "echo 'Connected to EC2'"

      
      