name: shiftSync

on:
  push:
    branches:
      - testing
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.5

      # - name: Install Make
      #   run: |
      #     sudo apt update
      #     sudo apt install -y make

      # - name: Test
      #   run: make test    

      # - name: Build
      #   run: make build

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
         
          script: |
            echo "Connected to EC2 instance"
            cd shiftSync
            git pull
            pwd
            go version
            echo $PATH
            sudo systemctl restart shiftsync.service
          debug: true
      
      