steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up Go
    uses: actions/setup-go@v3
    with:
      go-version: 1.20.5

  - name: Install Make
    run: |
      sudo apt update
      sudo apt install -y make

  - name: Build
    run: make build

  - name: Test
    run: make test
