name: shiftSync

on: 
  push:
    branches: [ testing ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.5

      - name: Install Make
        run: |
          sudo apt update
          sudo apt install -y make

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 34.228.140.218
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Connected to EC2 instance"
            cd shiftSync
            git pull
            cd cmd/api
            go build
            cd ../../
            systemctl restart shiftsync.service
      
      